feign:
  client:
    config:
      default:
        connectTimeout: 10000
      jplaceholder:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        url : http://jsonplaceholder.typicode.com/
